
@api = http://localhost:3000/login

GET {{api}}
###
POST {{api}}

###
GET {{api}}/200000
###

GET {{api}}/tasks
###

###
POST {{api}}/check
Content-Type: application/json

{
    "dev":"ANDROIDZ",
    "uzer":"s.zegarra@hotmail.com",
    "pass":"123"
}

###
POST {{api}}/dev
Content-Type: application/json

{
    "dispositivo":"ANDROIDZ"
}

###
DELETE {{api}}/9