
@api = http://localhost:3000/tasks

GET {{api}}
###
POST {{api}}

###
GET {{api}}/200000
###

GET {{api}}/tasks
###

###
POST {{api}}
Content-Type: application/json

{
    "id":55,
    "razon":"nuevo jsj"
}

###
DELETE {{api}}/9